/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sample_offset_cci.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(dc578dfdcd95f1558e9e73063e94a4c1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/doa/sample_offset_cci.h>
// pydoc.h is automatically generated in the build directory
#include <sample_offset_cci_pydoc.h>

void bind_sample_offset_cci(py::module& m)
{

    using sample_offset_cci    = gr::doa::sample_offset_cci;


    py::class_<sample_offset_cci, gr::block, gr::basic_block,
        std::shared_ptr<sample_offset_cci>>(m, "sample_offset_cci", D(sample_offset_cci))

        .def(py::init(&sample_offset_cci::make),
           D(sample_offset_cci,make)
        )




        ;




}








